import { Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import type {
  IntentPatch,
  PlanRefinementRequest,
  PlanRefinementResponse,
  PreservationPatch,
} from '@blendify/contracts/ai-service';
import { EMPTY_AI_PRESERVATION } from '@/domain/ai/ai-intent-patch';
import type { AiIntent } from '@/domain/ai/ai-intent';
import {
  diffIntents,
  diffPlaylistTracks,
} from '@/domain/ai/ai-refinement-diff';
import {
  AI_SESSION_RECORD_VERSION,
  type AiPendingRefinement,
  type AiSession,
  type AiSessionDestination,
  type AiSessionExecution,
} from '@/domain/ai/ai-session';
import { AiInterpretationError } from '@/domain/errors/ai-interpretation.error';
import {
  AiSessionError,
  type AiSessionErrorCode,
} from '@/domain/errors/ai-session.error';
import { Artist } from '@/domain/artist/artist.entity';
import { GeneratedPlaylist } from '@/domain/playlist/generated-playlist';
import type { AiSessionRepositoryPort } from '@/domain/repositories/ai-session.repository.port';
import { Track } from '@/domain/track/track.entity';
import { ArtistId } from '@/domain/value-objects/artist-id.vo';
import { TrackId } from '@/domain/value-objects/track-id.vo';
import { createSpotifyQuotaError } from '@/infrastructure/spotify/spotify-quota-error';
import {
  AI_REFINEMENT_LEASE_MS,
  AI_REFINEMENT_LEASE_RENEW_INTERVAL_MS,
  DEFAULT_AI_REFINEMENTS_PER_SESSION,
} from '@/application/services/ai-refinement.policy';
import { AiIntentResolver } from '@/application/services/ai-intent-resolver.service';
import { AiRefinementCandidateBuilder } from '@/application/services/ai-refinement-candidate.service';
import type {
  GeneratePlaylistUseCase,
  PlaylistGenerationRequest,
} from './generate-playlist.use-case';
import { ProposeAiRefinementUseCase } from './propose-ai-refinement.use-case';

const TOKEN = 'session-token';
const NOW = new Date('2026-09-28T12:00:00.000Z');
const GENERATED_AT = '2026-09-28T11:55:00.000Z';
const EXPIRES_AT = '2026-09-28T12:20:00.000Z';
const REFINEMENT =
  'Make it less mainstream, remove Interpol and keep the first two';
const NO_NAMES = { add: [], remove: [] };

const INTENT: AiIntent = {
  kind: 'artist_mix',
  artists: ['Radiohead', 'Interpol'],
  genres: [],
  seedTracks: [],
  targetTrackCount: 3,
  targetDurationMinutes: null,
  mood: null,
  popularity: 'balanced',
  orderMode: null,
  excludeArtists: ['Coldplay'],
  excludeTracks: [],
  unsupportedConstraints: [],
};

const GENERATED: AiSessionExecution = {
  status: 'generated',
  startedAt: GENERATED_AT,
  completedAt: GENERATED_AT,
  result: {
    playlist: {
      name: 'Blendify · Mix · Radiohead + Interpol',
      description: 'Generated by Blendify',
      seeds: [
        { type: 'artist', id: '4Z8W4fKeB5YxbusRsdQVPb', name: 'Radiohead' },
      ],
      tracks: [
        '6LgJvl0Xdtc73RJ1mmpotq',
        '3SVAN3BRByDmHOhKyIDxfC',
        '0ofHAoxe9vBkTCp2UQIavz',
      ].map((id, index) => ({
        id,
        name: `Provider song ${index + 1}`,
        artistId: '4Z8W4fKeB5YxbusRsdQVPb',
        artistName: 'Provider artist name',
        durationMs: 215_000 + index,
        popularity: 61,
        uri: `spotify:track:${id}`,
        albumImageUrl: 'https://i.scdn.co/image/ab67616d0000b273',
      })),
    },
    recipe: {
      version: 1,
      kind: 'artist_mix',
      tracksPerSeed: 2,
      seeds: [{ id: '4Z8W4fKeB5YxbusRsdQVPb', name: 'Radiohead' }],
      popularity: 'balanced',
      orderMode: 'random',
    },
    durationMs: 645_003,
    unmetConstraints: [],
  },
};

function storedSession(overrides: Partial<AiSession> = {}): AiSession {
  return {
    version: AI_SESSION_RECORD_VERSION,
    ownerUserId: null,
    originalPrompt: 'Radiohead and Interpol, 3 songs, no Coldplay',
    promptVersion: 'intent-v3',
    aiSafe: { intent: INTENT, preservation: EMPTY_AI_PRESERVATION },
    clarification: null,
    execution: GENERATED,
    destination: null,
    refinementAttempts: 0,
    pendingRefinement: null,
    createdAt: GENERATED_AT,
    updatedAt: GENERATED_AT,
    expiresAt: EXPIRES_AT,
    ...overrides,
  };
}

const CURRENT_TRACK_IDS = [
  '6LgJvl0Xdtc73RJ1mmpotq',
  '3SVAN3BRByDmHOhKyIDxfC',
  '0ofHAoxe9vBkTCp2UQIavz',
];

function generatedTrack(id: string): Track {
  return Track.create({
    id: TrackId.create(id),
    name: `Rarity ${id}`,
    artistId: ArtistId.create('4Z8W4fKeB5YxbusRsdQVPb'),
    artistName: 'Radiohead',
    durationMs: 200_000,
    popularity: 20,
    uri: `spotify:track:${id}`,
  });
}

function freshGeneration(ids = ['new-1', 'new-2', 'new-3']): GeneratedPlaylist {
  return GeneratedPlaylist.create({
    name: 'Blendify · Mix · Radiohead',
    generation: {
      version: 1,
      kind: 'artist_mix',
      tracksPerSeed: 3,
      seeds: [{ id: '4Z8W4fKeB5YxbusRsdQVPb', name: 'Radiohead' }],
      popularity: 'rarities',
      orderMode: 'random',
    },
    seeds: [
      { type: 'artist', id: '4Z8W4fKeB5YxbusRsdQVPb', name: 'Radiohead' },
    ],
    tracks: ids.map(generatedTrack),
  });
}

const UNCHANGED_PATCH = {
  kind: null,
  artists: NO_NAMES,
  genres: NO_NAMES,
  seedTracks: NO_NAMES,
  targetTrackCount: null,
  targetDurationMinutes: null,
  mood: null,
  popularity: null,
  orderMode: null,
  excludeArtists: NO_NAMES,
  excludeTracks: NO_NAMES,
};
const UNCHANGED_PRESERVATION = {
  firstTracks: null,
  positions: { add: [], remove: [] },
  artists: NO_NAMES,
};

function plan(
  result: PlanRefinementResponse['result'],
): PlanRefinementResponse {
  return { promptVersion: 'refinement-v1', result };
}

function lessMainstream(): PlanRefinementResponse {
  return plan({
    outcome: 'interpreted',
    patch: {
      ...UNCHANGED_PATCH,
      artists: { add: [], remove: ['Interpol'] },
      popularity: { operation: 'set', value: 'rarities' },
    },
    preservation: {
      ...UNCHANGED_PRESERVATION,
      firstTracks: { operation: 'set', value: 2 },
    },
    unsupportedConstraints: [],
  });
}

function createWorld(
  session: AiSession | null = storedSession(),
  config: Record<string, string> = {},
) {
  const store = new Map<string, AiSession>();
  if (session) {
    store.set(TOKEN, session);
  }
  let lock: string | null = null;
  const sessions = {
    save: jest.fn(),
    find: jest.fn((token: string) => Promise.resolve(store.get(token) ?? null)),
    saveGenerationOutcome: jest.fn(),
    acquireGenerationLock: jest.fn(),
    renewGenerationLock: jest.fn(),
    releaseGenerationLock: jest.fn(),
    hasGenerationLock: jest.fn(),
    savePublishOutcome: jest.fn(),
    acquireDestinationClaim: jest.fn(),
    renewDestinationClaim: jest.fn(),
    releaseDestinationClaim: jest.fn(),
    hasDestinationClaim: jest.fn(),
    saveIfUnchanged: jest.fn(
      (
        token: string,
        next: AiSession,
        expectedUpdatedAt: string,
        _ttlMs: number,
      ) => {
        if (store.get(token)?.updatedAt !== expectedUpdatedAt) {
          return Promise.resolve(false);
        }
        store.set(token, next);
        return Promise.resolve(true);
      },
    ),
    acquireRefinementLock: jest.fn((_token: string, _ttlMs: number) => {
      if (lock) {
        return Promise.resolve<string | null>(null);
      }
      lock = 'lock-1';
      return Promise.resolve<string | null>(lock);
    }),
    renewRefinementLock: jest.fn(() => Promise.resolve(true)),
    releaseRefinementLock: jest.fn((_token: string, lockId: string) => {
      if (lock === lockId) {
        lock = null;
      }
      return Promise.resolve();
    }),
  } satisfies AiSessionRepositoryPort;
  const planner = {
    planRefinement: jest.fn<
      Promise<PlanRefinementResponse>,
      [PlanRefinementRequest]
    >(() => Promise.resolve(lessMainstream())),
  };
  const catalog = {
    searchArtists: jest.fn((name: string) =>
      Promise.resolve([
        Artist.create({
          id: ArtistId.create(`${name.toLowerCase()}-id`),
          name,
        }),
      ]),
    ),
    searchTracks: jest.fn(() => Promise.resolve([])),
    resolveTrack: jest.fn(() => Promise.resolve(null)),
    getArtistsByIds: jest.fn(() => Promise.resolve([])),
  };
  const catalogs = { forMarket: jest.fn(() => catalog) };
  const generator = {
    execute: jest.fn<Promise<GeneratedPlaylist>, [PlaylistGenerationRequest]>(
      () => Promise.resolve(freshGeneration()),
    ),
  };
  const candidates = new AiRefinementCandidateBuilder(
    new AiIntentResolver(catalogs),
    generator as unknown as GeneratePlaylistUseCase,
  );
  const useCase = new ProposeAiRefinementUseCase(
    sessions,
    planner,
    candidates,
    new ConfigService(config),
  );
  return {
    useCase,
    sessions,
    planner,
    catalogs,
    generator,
    store,
    holdLock: () => {
      lock = 'someone-else';
    },
    takeOverLock: () => {
      lock = 'lock-2';
    },
    dismissPending: () => {
      const current = store.get(TOKEN);
      if (current) {
        store.set(TOKEN, { ...current, pendingRefinement: null });
      }
    },
  };
}

async function errorCode(
  promise: Promise<unknown>,
): Promise<AiSessionErrorCode> {
  const error: unknown = await promise.catch((caught: unknown) => caught);
  expect(error).toBeInstanceOf(AiSessionError);
  return (error as AiSessionError).code;
}

function execute(
  world: ReturnType<typeof createWorld>,
  userId: string | null = null,
) {
  return world.useCase.execute({
    token: TOKEN,
    userId,
    refinement: REFINEMENT,
  });
}

describe('ProposeAiRefinementUseCase', () => {
  beforeEach(() => {
    jest.useFakeTimers({ now: NOW });
    jest.spyOn(Logger.prototype, 'log').mockImplementation();
    jest.spyOn(Logger.prototype, 'warn').mockImplementation();
  });

  afterEach(() => {
    jest.useRealTimers();
    jest.restoreAllMocks();
  });

  it('sends only the current AI-safe intent, preservation and refinement to the planner', async () => {
    const world = createWorld(
      storedSession({
        aiSafe: {
          intent: INTENT,
          preservation: {
            firstTracks: null,
            positions: [3],
            artists: ['Radiohead'],
          },
        },
      }),
    );

    await execute(world);

    const [[request]] = world.planner.planRefinement.mock.calls;
    expect(request).toEqual({
      intent: INTENT,
      preservation: {
        firstTracks: null,
        positions: [3],
        artists: ['Radiohead'],
      },
      refinement: REFINEMENT,
    });
    const serialized = JSON.stringify(request);
    for (const providerValue of [
      '6LgJvl0Xdtc73RJ1mmpotq',
      '4Z8W4fKeB5YxbusRsdQVPb',
      'spotify:track',
      'i.scdn.co',
      'Provider song',
      'Provider artist name',
      '215000',
      'tracksPerSeed',
      'Blendify · Mix',
    ]) {
      expect(serialized).not.toContain(providerValue);
    }
  });

  it('stores the proposal as pending without changing the applied intent, preview or destination', async () => {
    const world = createWorld();

    const { session } = await execute(world);

    expect(session.pendingRefinement).toMatchObject({
      status: 'proposed',
      promptVersion: 'refinement-v1',
      proposedAt: NOW.toISOString(),
      aiSafe: {
        intent: { ...INTENT, artists: ['Radiohead'], popularity: 'rarities' },
        preservation: { firstTracks: 2, positions: [], artists: [] },
        notApplied: [],
      },
      candidate: { status: 'ready', preservedPositions: [1, 2] },
    });
    expect(session.aiSafe).toEqual({
      intent: INTENT,
      preservation: EMPTY_AI_PRESERVATION,
    });
    expect(session.execution).toBe(GENERATED);
    expect(session.destination).toBeNull();
    expect(session.refinementAttempts).toBe(1);
    expect(world.store.get(TOKEN)).toEqual(session);
  });

  it('keeps the session TTL on every write', async () => {
    const world = createWorld();

    const { session } = await execute(world);

    const remainingMs = Date.parse(EXPIRES_AT) - NOW.getTime();
    expect(session.expiresAt).toBe(EXPIRES_AT);
    expect(
      world.sessions.saveIfUnchanged.mock.calls.map((call) => call[3]),
    ).toEqual([remainingMs, remainingMs]);
  });

  it.each([
    [
      'a clarification',
      plan({
        outcome: 'needs_clarification',
        clarification: {
          reason: 'ambiguous_request',
          unsupportedConstraints: [
            { category: 'duration', userText: 'make it shorter' },
          ],
        },
      }),
      'needs_clarification',
    ],
    [
      'an unsupported-only refinement',
      plan({
        outcome: 'interpreted',
        patch: UNCHANGED_PATCH,
        preservation: UNCHANGED_PRESERVATION,
        unsupportedConstraints: [
          { category: 'activity', userText: 'for running' },
        ],
      }),
      'needs_clarification',
    ],
  ])(
    'keeps the applied intent when the result is %s',
    async (_label, response, status) => {
      const world = createWorld();
      world.planner.planRefinement.mockResolvedValue(response);

      const { session } = await execute(world);

      expect(session.pendingRefinement?.status).toBe(status);
      expect(session.aiSafe.intent).toEqual(INTENT);
      expect(session.execution).toBe(GENERATED);
    },
  );

  it('keeps the applied state and counts the attempt when interpretation fails', async () => {
    const world = createWorld();
    world.planner.planRefinement.mockRejectedValue(
      AiInterpretationError.timedOut(),
    );

    await expect(execute(world)).rejects.toBeInstanceOf(AiInterpretationError);

    const stored = world.store.get(TOKEN);
    expect(stored?.aiSafe.intent).toEqual(INTENT);
    expect(stored?.pendingRefinement).toBeNull();
    expect(stored?.execution).toBe(GENERATED);
    expect(stored?.refinementAttempts).toBe(1);
    expect(world.sessions.releaseRefinementLock).toHaveBeenCalledWith(
      TOKEN,
      'lock-1',
    );
  });

  it('interprets every refinement against the latest applied intent once the pending one is dismissed', async () => {
    const world = createWorld();

    await execute(world);
    world.dismissPending();
    await execute(world);

    const requests = world.planner.planRefinement.mock.calls.map(
      ([request]) => request,
    );
    expect(requests[1].intent).toEqual(INTENT);
    expect(world.store.get(TOKEN)?.refinementAttempts).toBe(2);
  });

  it('refuses a concurrent refinement of the same session without calling the planner', async () => {
    const world = createWorld();
    world.holdLock();

    expect(await errorCode(execute(world))).toBe('AI_REFINEMENT_IN_PROGRESS');
    expect(world.planner.planRefinement).not.toHaveBeenCalled();
    expect(world.sessions.saveIfUnchanged).not.toHaveBeenCalled();
  });

  it('holds the refinement lease for the configured lease duration and always releases it', async () => {
    const world = createWorld();

    await execute(world);

    expect(world.sessions.acquireRefinementLock).toHaveBeenCalledWith(
      TOKEN,
      AI_REFINEMENT_LEASE_MS,
    );
    expect(world.sessions.releaseRefinementLock).toHaveBeenCalledWith(
      TOKEN,
      'lock-1',
    );
  });

  it('never overwrites a session that changed while the refinement was interpreted', async () => {
    const world = createWorld();
    world.planner.planRefinement.mockImplementation(() => {
      const current = world.store.get(TOKEN) as AiSession;
      world.store.set(TOKEN, {
        ...current,
        destination: {
          status: 'publishing',
          attemptId: 'publish-1',
          startedAt: NOW.toISOString(),
          spotifyPlaylist: null,
        },
        updatedAt: new Date(NOW.getTime() + 1).toISOString(),
      });
      return Promise.resolve(lessMainstream());
    });

    expect(await errorCode(execute(world))).toBe('AI_REFINEMENT_SUPERSEDED');
    expect(world.store.get(TOKEN)?.destination?.status).toBe('publishing');
    expect(world.store.get(TOKEN)?.pendingRefinement).toBeNull();
  });

  it('never overwrites a destination written in the same millisecond as the reservation', async () => {
    const world = createWorld();
    world.planner.planRefinement.mockImplementation(() => {
      const current = world.store.get(TOKEN) as AiSession;
      world.store.set(TOKEN, {
        ...current,
        destination: {
          status: 'transfer_prepared',
          preparedAt: current.updatedAt,
          transfer: {
            url: 'https://soundiiz.com/go/import-playlist/abc',
            expiresAt: EXPIRES_AT,
            trackCount: 3,
          },
        },
      });
      return Promise.resolve(lessMainstream());
    });

    expect(await errorCode(execute(world))).toBe('AI_REFINEMENT_SUPERSEDED');
    expect(world.store.get(TOKEN)?.destination?.status).toBe(
      'transfer_prepared',
    );
  });

  it.each<[string, Partial<AiSession>, AiSessionErrorCode]>([
    ['not generated yet', { execution: null }, 'AI_PLAYLIST_NOT_GENERATED'],
    [
      'still generating',
      {
        execution: {
          status: 'generating',
          attemptId: 'a',
          startedAt: GENERATED_AT,
        },
      },
      'AI_PLAYLIST_NOT_GENERATED',
    ],
    [
      'waiting for a first-turn clarification',
      {
        clarification: {
          reason: 'ambiguous_request',
          seedType: null,
          limit: null,
          names: [],
          unsupportedConstraints: [],
          options: [],
        },
      },
      'AI_SESSION_NOT_READY',
    ],
    ...(
      [
        {
          status: 'published',
          publishedAt: NOW.toISOString(),
          spotifyPlaylist: {
            spotifyId: '37i9dQZF1DX0XUsuxWHRQd',
            spotifyUrl: null,
          },
          savedToLibrary: true,
        },
        {
          status: 'publish_incomplete',
          failedAt: NOW.toISOString(),
          spotifyPlaylist: null,
        },
        {
          status: 'publishing',
          attemptId: 'publish-1',
          startedAt: NOW.toISOString(),
          spotifyPlaylist: null,
        },
        {
          status: 'transfer_prepared',
          preparedAt: NOW.toISOString(),
          transfer: {
            url: 'https://soundiiz.com/go/import-playlist/abc',
            expiresAt: '2026-09-28T11:00:00.000Z',
            trackCount: 3,
          },
        },
      ] satisfies AiSessionDestination[]
    ).map((destination): [string, Partial<AiSession>, AiSessionErrorCode] => [
      `already ${destination.status}`,
      { destination },
      'AI_REFINEMENT_UNAVAILABLE',
    ]),
    [
      'out of refinements',
      { refinementAttempts: DEFAULT_AI_REFINEMENTS_PER_SESSION },
      'AI_REFINEMENT_LIMIT_REACHED',
    ],
  ])(
    'refuses a session %s without any planner call or write',
    async (_label, overrides, code) => {
      const world = createWorld(storedSession(overrides));

      expect(await errorCode(execute(world))).toBe(code);
      expect(world.planner.planRefinement).not.toHaveBeenCalled();
      expect(world.sessions.saveIfUnchanged).not.toHaveBeenCalled();
      expect(world.sessions.acquireRefinementLock).not.toHaveBeenCalled();
    },
  );

  describe('while a refinement is pending', () => {
    const base = {
      id: 'pending-b',
      promptVersion: 'refinement-v2',
      proposedAt: GENERATED_AT,
    };
    const proposed = {
      ...base,
      status: 'proposed' as const,
      aiSafe: {
        intent: { ...INTENT, popularity: 'rarities' as const },
        preservation: EMPTY_AI_PRESERVATION,
        notApplied: [],
      },
    };
    const pendingStates: [string, AiPendingRefinement][] = [
      [
        'candidate_ready',
        {
          ...proposed,
          candidate: {
            status: 'ready',
            result: GENERATED.result,
            preservedPositions: [],
            diff: {
              tracks: diffPlaylistTracks(
                GENERATED.result.playlist.tracks,
                GENERATED.result.playlist.tracks,
              ),
              intent: diffIntents(INTENT, proposed.aiSafe.intent),
            },
          },
        },
      ],
      [
        'candidate_failed',
        {
          ...proposed,
          candidate: {
            status: 'failed',
            failure: {
              code: 'NO_TRACKS_FOUND',
              category: 'insufficient_results',
              retryAfterSeconds: null,
              seedNotFound: null,
            },
          },
        },
      ],
      [
        'needs_clarification',
        {
          ...base,
          status: 'needs_clarification',
          clarification: {
            reason: 'preserved_artist_not_found',
            seedType: 'artist',
            limit: null,
            names: ['Portishead'],
            unsupportedConstraints: [],
          },
        },
      ],
      ['unchanged', { ...base, status: 'unchanged' }],
    ];

    it.each(pendingStates)(
      'refuses a new refinement while %s is pending without planner, provider or write calls',
      async (_label, pendingRefinement) => {
        const session = storedSession({
          pendingRefinement,
          updatedAt: '2026-09-28T11:58:00.000Z',
        });
        const world = createWorld(session);

        expect(await errorCode(execute(world))).toBe('AI_REFINEMENT_PENDING');
        expect(world.planner.planRefinement).not.toHaveBeenCalled();
        expect(world.catalogs.forMarket).not.toHaveBeenCalled();
        expect(world.generator.execute).not.toHaveBeenCalled();
        expect(world.sessions.acquireRefinementLock).not.toHaveBeenCalled();
        expect(world.sessions.saveIfUnchanged).not.toHaveBeenCalled();
        expect(world.store.get(TOKEN)).toBe(session);
      },
    );

    it('refuses a refinement whose pending state appears after the lease is acquired', async () => {
      const world = createWorld();
      const [, pendingRefinement] = pendingStates[0];
      world.sessions.acquireRefinementLock.mockImplementationOnce(() => {
        const current = world.store.get(TOKEN) as AiSession;
        world.store.set(TOKEN, { ...current, pendingRefinement });
        return Promise.resolve<string | null>('lock-1');
      });

      expect(await errorCode(execute(world))).toBe('AI_REFINEMENT_PENDING');
      expect(world.planner.planRefinement).not.toHaveBeenCalled();
      expect(world.generator.execute).not.toHaveBeenCalled();
      expect(world.sessions.saveIfUnchanged).not.toHaveBeenCalled();
      expect(world.store.get(TOKEN)?.pendingRefinement).toBe(pendingRefinement);
      expect(world.sessions.releaseRefinementLock).toHaveBeenCalledWith(
        TOKEN,
        'lock-1',
      );
    });
  });

  it('reads the per-session limit from configuration', async () => {
    const world = createWorld(storedSession({ refinementAttempts: 1 }), {
      AI_REFINEMENTS_PER_SESSION: '2',
    });

    await execute(world);
    world.dismissPending();

    expect(await errorCode(execute(world))).toBe('AI_REFINEMENT_LIMIT_REACHED');
    expect(world.planner.planRefinement).toHaveBeenCalledTimes(1);
  });

  it('fails fast on an invalid per-session limit', () => {
    expect(() =>
      createWorld(storedSession(), { AI_REFINEMENTS_PER_SESSION: '0' }),
    ).toThrow('Invalid AI_REFINEMENTS_PER_SESSION');
  });

  it.each([
    ['missing', null, null],
    [
      'owned by another user',
      storedSession({ ownerUserId: 'user-1' }),
      'user-2',
    ],
    ['expired', storedSession({ expiresAt: '2026-09-28T11:59:59.000Z' }), null],
  ])('reports a %s session as not found', async (_label, session, userId) => {
    const world = createWorld(session);

    expect(await errorCode(execute(world, userId))).toBe(
      'AI_SESSION_NOT_FOUND',
    );
    expect(world.planner.planRefinement).not.toHaveBeenCalled();
  });

  it('refines an authenticated session only for its owner', async () => {
    const world = createWorld(storedSession({ ownerUserId: 'user-1' }));

    const { session } = await execute(world, 'user-1');

    expect(session.pendingRefinement?.status).toBe('proposed');
    expect(session.ownerUserId).toBe('user-1');
  });

  it('logs metadata only', async () => {
    const log = jest.spyOn(Logger.prototype, 'log').mockImplementation();
    const world = createWorld();

    await execute(world);

    const logged = log.mock.calls
      .map(([message]) => String(message))
      .join('\n');
    expect(JSON.parse(logged)).toEqual({
      event: 'ai.operation',
      requestId: null,
      operation: 'refinement',
      result: 'candidate_ready',
      durationMs: expect.any(Number) as number,
      candidateTrackCount: expect.any(Number) as number,
      addedCount: expect.any(Number) as number,
      removedCount: expect.any(Number) as number,
      movedCount: expect.any(Number) as number,
      promptVersion: 'refinement-v1',
      candidateAttempted: true,
      candidateStrategy: 'regenerate',
      refinementAttempt: 1,
      interpretationMs: expect.any(Number) as number,
      candidateMs: expect.any(Number) as number,
    });
    expect(logged).not.toContain(REFINEMENT);
    expect(logged).not.toContain('Radiohead');
  });
  describe('candidate execution', () => {
    function interpretedPlan(
      patch: Partial<IntentPatch>,
      preservation: Partial<PreservationPatch> = {},
    ): PlanRefinementResponse {
      return plan({
        outcome: 'interpreted',
        patch: { ...UNCHANGED_PATCH, ...patch },
        preservation: { ...UNCHANGED_PRESERVATION, ...preservation },
        unsupportedConstraints: [],
      });
    }

    function pendingCandidate(session: AiSession) {
      const pending = session.pendingRefinement;
      if (pending?.status !== 'proposed') {
        throw new Error('Expected a proposed refinement.');
      }
      return pending.candidate;
    }

    function candidateTrackIds(session: AiSession): string[] {
      const candidate = pendingCandidate(session);
      if (candidate.status !== 'ready') {
        throw new Error('Expected a ready candidate.');
      }
      return candidate.result.playlist.tracks.map((track) => track.id);
    }

    it('builds the candidate from the proposed intent with preserved first tracks, leaving the applied preview intact', async () => {
      const world = createWorld();

      const { session } = await execute(world);

      expect(candidateTrackIds(session)).toEqual([
        CURRENT_TRACK_IDS[0],
        CURRENT_TRACK_IDS[1],
        'new-1',
      ]);
      expect(world.generator.execute).toHaveBeenCalledTimes(1);
      expect(world.generator.execute.mock.calls[0][0]).toMatchObject({
        kind: 'artist_mix',
        popularity: 'rarities',
        artistIds: ['radiohead-id'],
      });
      expect(session.execution).toBe(GENERATED);
      expect(session.aiSafe.intent).toEqual(INTENT);
      expect(session.destination).toBeNull();
    });

    it('stores a deterministic diff and the preserved positions with the candidate', async () => {
      const world = createWorld();

      const { session } = await execute(world);

      const candidate = pendingCandidate(session);
      expect(candidate).toMatchObject({
        status: 'ready',
        preservedPositions: [1, 2],
        diff: {
          tracks: {
            added: [{ trackId: 'new-1', position: 3 }],
            removed: [{ trackId: CURRENT_TRACK_IDS[2], position: 3 }],
            moved: [],
            retainedCount: 2,
            replacedCount: 1,
          },
          intent: [
            { field: 'artists', added: [], removed: ['Interpol'] },
            { field: 'popularity', from: 'balanced', to: 'rarities' },
          ],
        },
      });
    });

    it('reorders the current tracks for an order-only refinement with zero provider calls', async () => {
      const world = createWorld();
      world.planner.planRefinement.mockResolvedValue(
        interpretedPlan({ orderMode: { operation: 'set', value: 'title' } }),
      );

      const { session } = await execute(world);

      expect(candidateTrackIds(session)).toEqual(CURRENT_TRACK_IDS);
      expect(pendingCandidate(session)).toMatchObject({
        status: 'ready',
        result: { recipe: { orderMode: 'title', popularity: 'balanced' } },
      });
      expect(world.catalogs.forMarket).not.toHaveBeenCalled();
      expect(world.generator.execute).not.toHaveBeenCalled();
    });

    it('stores a settings-only candidate when the excluded artist is not in the playlist', async () => {
      const world = createWorld();
      world.planner.planRefinement.mockResolvedValue(
        interpretedPlan({ excludeArtists: { add: ['Muse'], remove: [] } }),
      );

      const { session } = await execute(world);

      expect(candidateTrackIds(session)).toEqual(CURRENT_TRACK_IDS);
      expect(session.pendingRefinement).toMatchObject({
        status: 'proposed',
        aiSafe: { intent: { excludeArtists: ['Coldplay', 'Muse'] } },
        candidate: {
          status: 'ready',
          diff: {
            tracks: { added: [], removed: [], moved: [] },
            intent: [{ field: 'excludeArtists', added: ['Muse'], removed: [] }],
          },
        },
      });
      expect(world.generator.execute).not.toHaveBeenCalled();
    });

    it('reports repeating an active exclusion as unchanged without building a candidate', async () => {
      const world = createWorld();
      world.planner.planRefinement.mockResolvedValue(
        interpretedPlan({ excludeArtists: { add: ['coldplay'], remove: [] } }),
      );

      const { session } = await execute(world);

      expect(session.pendingRefinement).toMatchObject({ status: 'unchanged' });
      expect(world.catalogs.forMarket).not.toHaveBeenCalled();
      expect(world.generator.execute).not.toHaveBeenCalled();
    });

    it('asks for clarification instead of excluding an artist named like a genre', async () => {
      const world = createWorld();
      world.planner.planRefinement.mockResolvedValue(
        interpretedPlan({ excludeArtists: { add: ['rock'], remove: [] } }),
      );

      const { session } = await execute(world);

      expect(session.pendingRefinement).toMatchObject({
        status: 'needs_clarification',
        clarification: {
          reason: 'unsupported_constraint',
          unsupportedConstraints: [
            { category: 'genre_exclusion', userText: 'rock' },
          ],
        },
      });
      expect(world.generator.execute).not.toHaveBeenCalled();
    });

    it('composes a relative duration against the persisted target and validates that target', async () => {
      const world = createWorld(
        storedSession({
          aiSafe: {
            intent: {
              ...INTENT,
              targetTrackCount: null,
              targetDurationMinutes: 30,
            },
            preservation: EMPTY_AI_PRESERVATION,
          },
        }),
      );
      world.planner.planRefinement.mockResolvedValue(
        interpretedPlan({
          targetDurationMinutes: { operation: 'adjust', deltaMinutes: 10 },
        }),
      );

      const { session } = await execute(world);

      expect(session.pendingRefinement).toMatchObject({
        status: 'proposed',
        aiSafe: { intent: { targetDurationMinutes: 40 } },
      });
    });

    it('trims a count decrease with zero provider calls', async () => {
      const world = createWorld();
      world.planner.planRefinement.mockResolvedValue(
        interpretedPlan({ targetTrackCount: { operation: 'set', value: 2 } }),
      );

      const { session } = await execute(world);

      expect(candidateTrackIds(session)).toHaveLength(2);
      expect(world.generator.execute).not.toHaveBeenCalled();
    });

    it('fills a count increase from one bounded generation, keeping every current track', async () => {
      const world = createWorld();
      world.planner.planRefinement.mockResolvedValue(
        interpretedPlan({ targetTrackCount: { operation: 'set', value: 5 } }),
      );

      const { session } = await execute(world);

      expect(candidateTrackIds(session)).toEqual([
        ...CURRENT_TRACK_IDS,
        'new-1',
        'new-2',
      ]);
      expect(world.generator.execute).toHaveBeenCalledTimes(1);
      expect(world.generator.execute.mock.calls[0][0]).toMatchObject({
        popularity: 'balanced',
        tracksPerSeed: 4,
      });
    });

    it('never runs a second generation and refuses the candidate when the pool cannot reach the requested count', async () => {
      const world = createWorld();
      world.generator.execute.mockResolvedValue(
        freshGeneration([CURRENT_TRACK_IDS[0]]),
      );
      world.planner.planRefinement.mockResolvedValue(
        interpretedPlan({ targetTrackCount: { operation: 'set', value: 10 } }),
      );

      const { session } = await execute(world);

      expect(world.generator.execute).toHaveBeenCalledTimes(1);
      expect(pendingCandidate(session)).toEqual({
        status: 'failed',
        failure: {
          code: 'AI_REFINEMENT_CONSTRAINTS_UNMET',
          category: 'insufficient_results',
          retryAfterSeconds: null,
          seedNotFound: null,
        },
      });
      expect(session.execution).toBe(GENERATED);
    });

    it.each([
      [
        'a preserved artist that the refinement excludes',
        interpretedPlan(
          { excludeArtists: { add: ['Provider artist name'], remove: [] } },
          { artists: { add: ['Provider artist name'], remove: [] } },
        ),
        'conflicting_changes',
      ],
      [
        'more preserved tracks than the new count',
        interpretedPlan(
          { targetTrackCount: { operation: 'set', value: 2 } },
          { firstTracks: { operation: 'set', value: 3 } },
        ),
        'conflicting_changes',
      ],
      [
        'a preserved artist missing from the playlist',
        interpretedPlan(
          {},
          { artists: { add: ['Massive Attack'], remove: [] } },
        ),
        'preserved_artist_not_found',
      ],
    ])(
      'returns a typed clarification for %s without generating',
      async (_label, response, reason) => {
        const world = createWorld();
        world.planner.planRefinement.mockResolvedValue(response);

        const { session } = await execute(world);

        expect(session.pendingRefinement).toMatchObject({
          status: 'needs_clarification',
          clarification: { reason },
        });
        expect(world.generator.execute).not.toHaveBeenCalled();
        expect(world.catalogs.forMarket).not.toHaveBeenCalled();
        expect(session.execution).toBe(GENERATED);
      },
    );

    it('stores a typed provider failure and keeps the applied preview', async () => {
      const world = createWorld();
      world.generator.execute.mockRejectedValue(
        createSpotifyQuotaError({
          retryAfterSeconds: 120,
          reason: 'RATE_LIMITED',
        }),
      );

      const { session } = await execute(world);

      expect(pendingCandidate(session)).toEqual({
        status: 'failed',
        failure: expect.objectContaining({
          category: 'provider_rate_limited',
          retryAfterSeconds: 120,
        }) as object,
      });
      expect(session.execution).toBe(GENERATED);
      expect(session.aiSafe.intent).toEqual(INTENT);
      expect(world.planner.planRefinement).toHaveBeenCalledTimes(1);
    });

    it('stores a typed seed-not-found failure when a proposed artist cannot be resolved', async () => {
      const world = createWorld();
      world.planner.planRefinement.mockResolvedValue(
        interpretedPlan({ artists: { add: ['Radiohed'], remove: [] } }),
      );
      world.catalogs.forMarket.mockReturnValue({
        searchArtists: jest.fn(() => Promise.resolve([])),
        searchTracks: jest.fn(() => Promise.resolve([])),
        resolveTrack: jest.fn(() => Promise.resolve(null)),
        getArtistsByIds: jest.fn(() => Promise.resolve([])),
      } as never);

      const { session } = await execute(world);

      expect(pendingCandidate(session)).toEqual({
        status: 'failed',
        failure: {
          code: 'AI_SEED_NOT_FOUND',
          category: 'seed_not_found',
          retryAfterSeconds: null,
          seedNotFound: {
            seedType: 'artist',
            names: ['Radiohead', 'Interpol', 'Radiohed'],
          },
        },
      });
      expect(world.generator.execute).not.toHaveBeenCalled();
    });

    it('interprets the next refinement against the applied intent after a candidate is dismissed, without candidate data', async () => {
      const world = createWorld();
      await execute(world);
      world.dismissPending();
      world.planner.planRefinement.mockClear();

      await execute(world);

      const [[request]] = world.planner.planRefinement.mock.calls;
      expect(request).toEqual({
        intent: INTENT,
        preservation: EMPTY_AI_PRESERVATION,
        refinement: REFINEMENT,
      });
      const serialized = JSON.stringify(request);
      for (const providerValue of [
        ...CURRENT_TRACK_IDS,
        'new-1',
        'Rarity',
        'spotify:track',
        'rarities',
      ]) {
        expect(serialized).not.toContain(providerValue);
      }
    });

    describe('stale attempts', () => {
      function deferredGeneration() {
        let resolve: (playlist: GeneratedPlaylist) => void = () => undefined;
        let reject: (error: unknown) => void = () => undefined;
        const promise = new Promise<GeneratedPlaylist>((res, rej) => {
          resolve = res;
          reject = rej;
        });
        return { promise, resolve, reject };
      }

      async function loseLeaseDuringGeneration(
        world: ReturnType<typeof createWorld>,
      ) {
        const generation = deferredGeneration();
        world.generator.execute.mockReturnValue(generation.promise);
        world.sessions.renewRefinementLock.mockResolvedValue(false);
        const running = execute(world);
        await jest.advanceTimersByTimeAsync(0);
        expect(world.generator.execute).toHaveBeenCalledTimes(1);

        world.takeOverLock();
        await jest.advanceTimersByTimeAsync(
          AI_REFINEMENT_LEASE_RENEW_INTERVAL_MS,
        );
        return { running, generation };
      }

      it('never persists a late candidate success after losing the lease', async () => {
        const world = createWorld();
        const before = world.store.get(TOKEN);
        const { running, generation } = await loseLeaseDuringGeneration(world);

        generation.resolve(freshGeneration());

        expect(await errorCode(running)).toBe('AI_REFINEMENT_SUPERSEDED');
        expect(world.store.get(TOKEN)?.pendingRefinement).toBeNull();
        expect(world.store.get(TOKEN)?.execution).toBe(before?.execution);
      });

      it('never persists a late candidate failure after losing the lease', async () => {
        const world = createWorld();
        const { running, generation } = await loseLeaseDuringGeneration(world);

        generation.reject(
          createSpotifyQuotaError({ retryAfterSeconds: 1, reason: 'X' }),
        );

        expect(await errorCode(running)).toBe('AI_REFINEMENT_SUPERSEDED');
        expect(world.store.get(TOKEN)?.pendingRefinement).toBeNull();
      });

      it('never releases the lease of the attempt that took over', async () => {
        const world = createWorld();
        const { running, generation } = await loseLeaseDuringGeneration(world);

        generation.resolve(freshGeneration());
        await errorCode(running);

        expect(world.sessions.releaseRefinementLock).toHaveBeenCalledWith(
          TOKEN,
          'lock-1',
        );
        expect(await world.sessions.acquireRefinementLock(TOKEN, 1)).toBeNull();
      });

      it('lets only the newer attempt own the pending state when the session changed during generation', async () => {
        const world = createWorld();
        world.generator.execute.mockImplementation(() => {
          const current = world.store.get(TOKEN) as AiSession;
          world.store.set(TOKEN, {
            ...current,
            refinementAttempts: current.refinementAttempts + 1,
            updatedAt: new Date(NOW.getTime() + 5).toISOString(),
          });
          return Promise.resolve(freshGeneration());
        });

        expect(await errorCode(execute(world))).toBe(
          'AI_REFINEMENT_SUPERSEDED',
        );
        expect(world.store.get(TOKEN)?.pendingRefinement).toBeNull();
      });

      it('keeps a healthy long generation owned through heartbeat renewals', async () => {
        const world = createWorld();
        const generation = deferredGeneration();
        world.generator.execute.mockReturnValue(generation.promise);
        const running = execute(world);
        await jest.advanceTimersByTimeAsync(AI_REFINEMENT_LEASE_MS * 3);

        generation.resolve(freshGeneration());
        const { session } = await running;

        expect(world.sessions.renewRefinementLock).toHaveBeenCalled();
        expect(pendingCandidate(session).status).toBe('ready');
      });
    });
  });
});
