import { Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import type {
  PlanRefinementRequest,
  PlanRefinementResponse,
} from '@blendify/contracts/ai-service';
import { EMPTY_AI_PRESERVATION } from '@/domain/ai/ai-intent-patch';
import type { AiIntent } from '@/domain/ai/ai-intent';
import {
  AI_SESSION_RECORD_VERSION,
  type AiSession,
  type AiSessionDestination,
  type AiSessionExecution,
} from '@/domain/ai/ai-session';
import { AiInterpretationError } from '@/domain/errors/ai-interpretation.error';
import {
  AiSessionError,
  type AiSessionErrorCode,
} from '@/domain/errors/ai-session.error';
import type { AiSessionRepositoryPort } from '@/domain/repositories/ai-session.repository.port';
import {
  AI_REFINEMENT_LEASE_MS,
  DEFAULT_AI_REFINEMENTS_PER_SESSION,
} from '@/application/services/ai-refinement.policy';
import { ProposeAiRefinementUseCase } from './propose-ai-refinement.use-case';

const TOKEN = 'session-token';
const NOW = new Date('2026-09-28T12:00:00.000Z');
const GENERATED_AT = '2026-09-28T11:55:00.000Z';
const EXPIRES_AT = '2026-09-28T12:20:00.000Z';
const REFINEMENT =
  'Make it less mainstream, remove Interpol and keep the first two';
const NO_NAMES = { add: [], remove: [] };

const INTENT: AiIntent = {
  kind: 'artist_mix',
  artists: ['Radiohead', 'Interpol'],
  genres: [],
  seedTracks: [],
  targetTrackCount: 3,
  targetDurationMinutes: null,
  mood: null,
  popularity: 'balanced',
  orderMode: null,
  excludeArtists: ['Coldplay'],
  excludeTracks: [],
  unsupportedConstraints: [],
};

const GENERATED: AiSessionExecution = {
  status: 'generated',
  startedAt: GENERATED_AT,
  completedAt: GENERATED_AT,
  result: {
    playlist: {
      name: 'Blendify · Mix · Radiohead + Interpol',
      description: 'Generated by Blendify',
      seeds: [
        { type: 'artist', id: '4Z8W4fKeB5YxbusRsdQVPb', name: 'Radiohead' },
      ],
      tracks: [
        '6LgJvl0Xdtc73RJ1mmpotq',
        '3SVAN3BRByDmHOhKyIDxfC',
        '0ofHAoxe9vBkTCp2UQIavz',
      ].map((id, index) => ({
        id,
        name: `Provider song ${index + 1}`,
        artistId: '4Z8W4fKeB5YxbusRsdQVPb',
        artistName: 'Provider artist name',
        durationMs: 215_000 + index,
        popularity: 61,
        uri: `spotify:track:${id}`,
        albumImageUrl: 'https://i.scdn.co/image/ab67616d0000b273',
      })),
    },
    recipe: {
      version: 1,
      kind: 'artist_mix',
      tracksPerSeed: 2,
      seeds: [{ id: '4Z8W4fKeB5YxbusRsdQVPb', name: 'Radiohead' }],
      popularity: 'balanced',
      orderMode: 'random',
    },
    durationMs: 645_003,
    unmetConstraints: [],
  },
};

function storedSession(overrides: Partial<AiSession> = {}): AiSession {
  return {
    version: AI_SESSION_RECORD_VERSION,
    ownerUserId: null,
    originalPrompt: 'Radiohead and Interpol, 3 songs, no Coldplay',
    promptVersion: 'intent-v3',
    aiSafe: { intent: INTENT, preservation: EMPTY_AI_PRESERVATION },
    clarification: null,
    execution: GENERATED,
    destination: null,
    refinementAttempts: 0,
    pendingRefinement: null,
    createdAt: GENERATED_AT,
    updatedAt: GENERATED_AT,
    expiresAt: EXPIRES_AT,
    ...overrides,
  };
}

const UNCHANGED_PATCH = {
  kind: null,
  artists: NO_NAMES,
  genres: NO_NAMES,
  seedTracks: NO_NAMES,
  targetTrackCount: null,
  targetDurationMinutes: null,
  mood: null,
  popularity: null,
  orderMode: null,
  excludeArtists: NO_NAMES,
  excludeTracks: NO_NAMES,
};
const UNCHANGED_PRESERVATION = {
  firstTracks: null,
  positions: { add: [], remove: [] },
  artists: NO_NAMES,
};

function plan(
  result: PlanRefinementResponse['result'],
): PlanRefinementResponse {
  return { promptVersion: 'refinement-v1', result };
}

function lessMainstream(): PlanRefinementResponse {
  return plan({
    outcome: 'interpreted',
    patch: {
      ...UNCHANGED_PATCH,
      artists: { add: [], remove: ['Interpol'] },
      popularity: { operation: 'set', value: 'rarities' },
    },
    preservation: {
      ...UNCHANGED_PRESERVATION,
      firstTracks: { operation: 'set', value: 2 },
    },
    unsupportedConstraints: [],
  });
}

function createWorld(
  session: AiSession | null = storedSession(),
  config: Record<string, string> = {},
) {
  const store = new Map<string, AiSession>();
  if (session) {
    store.set(TOKEN, session);
  }
  let lock: string | null = null;
  const sessions = {
    save: jest.fn(),
    find: jest.fn((token: string) => Promise.resolve(store.get(token) ?? null)),
    saveGenerationOutcome: jest.fn(),
    acquireGenerationLock: jest.fn(),
    renewGenerationLock: jest.fn(),
    releaseGenerationLock: jest.fn(),
    hasGenerationLock: jest.fn(),
    savePublishOutcome: jest.fn(),
    acquireDestinationClaim: jest.fn(),
    renewDestinationClaim: jest.fn(),
    releaseDestinationClaim: jest.fn(),
    hasDestinationClaim: jest.fn(),
    saveIfUnchanged: jest.fn(
      (
        token: string,
        next: AiSession,
        expectedUpdatedAt: string,
        _ttlMs: number,
      ) => {
        if (store.get(token)?.updatedAt !== expectedUpdatedAt) {
          return Promise.resolve(false);
        }
        store.set(token, next);
        return Promise.resolve(true);
      },
    ),
    acquireRefinementLock: jest.fn((_token: string, _ttlMs: number) => {
      if (lock) {
        return Promise.resolve<string | null>(null);
      }
      lock = 'lock-1';
      return Promise.resolve<string | null>(lock);
    }),
    renewRefinementLock: jest.fn(() => Promise.resolve(true)),
    releaseRefinementLock: jest.fn((_token: string, lockId: string) => {
      if (lock === lockId) {
        lock = null;
      }
      return Promise.resolve();
    }),
  } satisfies AiSessionRepositoryPort;
  const planner = {
    planRefinement: jest.fn<
      Promise<PlanRefinementResponse>,
      [PlanRefinementRequest]
    >(() => Promise.resolve(lessMainstream())),
  };
  const useCase = new ProposeAiRefinementUseCase(
    sessions,
    planner,
    new ConfigService(config),
  );
  return {
    useCase,
    sessions,
    planner,
    store,
    holdLock: () => {
      lock = 'someone-else';
    },
  };
}

async function errorCode(
  promise: Promise<unknown>,
): Promise<AiSessionErrorCode> {
  const error: unknown = await promise.catch((caught: unknown) => caught);
  expect(error).toBeInstanceOf(AiSessionError);
  return (error as AiSessionError).code;
}

function execute(
  world: ReturnType<typeof createWorld>,
  userId: string | null = null,
) {
  return world.useCase.execute({
    token: TOKEN,
    userId,
    refinement: REFINEMENT,
  });
}

describe('ProposeAiRefinementUseCase', () => {
  beforeEach(() => {
    jest.useFakeTimers({ now: NOW });
    jest.spyOn(Logger.prototype, 'log').mockImplementation();
    jest.spyOn(Logger.prototype, 'warn').mockImplementation();
  });

  afterEach(() => {
    jest.useRealTimers();
    jest.restoreAllMocks();
  });

  it('sends only the current AI-safe intent, preservation and refinement to the planner', async () => {
    const world = createWorld(
      storedSession({
        aiSafe: {
          intent: INTENT,
          preservation: {
            firstTracks: null,
            positions: [3],
            artists: ['Radiohead'],
          },
        },
      }),
    );

    await execute(world);

    const [[request]] = world.planner.planRefinement.mock.calls;
    expect(request).toEqual({
      intent: INTENT,
      preservation: {
        firstTracks: null,
        positions: [3],
        artists: ['Radiohead'],
      },
      refinement: REFINEMENT,
    });
    const serialized = JSON.stringify(request);
    for (const providerValue of [
      '6LgJvl0Xdtc73RJ1mmpotq',
      '4Z8W4fKeB5YxbusRsdQVPb',
      'spotify:track',
      'i.scdn.co',
      'Provider song',
      'Provider artist name',
      '215000',
      'tracksPerSeed',
      'Blendify · Mix',
    ]) {
      expect(serialized).not.toContain(providerValue);
    }
  });

  it('stores the proposal as pending without changing the applied intent, preview or destination', async () => {
    const world = createWorld();

    const { session } = await execute(world);

    expect(session.pendingRefinement).toEqual({
      status: 'proposed',
      promptVersion: 'refinement-v1',
      proposedAt: NOW.toISOString(),
      aiSafe: {
        intent: { ...INTENT, artists: ['Radiohead'], popularity: 'rarities' },
        preservation: { firstTracks: 2, positions: [], artists: [] },
        notApplied: [],
      },
    });
    expect(session.aiSafe).toEqual({
      intent: INTENT,
      preservation: EMPTY_AI_PRESERVATION,
    });
    expect(session.execution).toBe(GENERATED);
    expect(session.destination).toBeNull();
    expect(session.refinementAttempts).toBe(1);
    expect(world.store.get(TOKEN)).toEqual(session);
  });

  it('keeps the session TTL on every write', async () => {
    const world = createWorld();

    const { session } = await execute(world);

    const remainingMs = Date.parse(EXPIRES_AT) - NOW.getTime();
    expect(session.expiresAt).toBe(EXPIRES_AT);
    expect(
      world.sessions.saveIfUnchanged.mock.calls.map((call) => call[3]),
    ).toEqual([remainingMs, remainingMs]);
  });

  it.each([
    [
      'a clarification',
      plan({
        outcome: 'needs_clarification',
        clarification: {
          reason: 'ambiguous_request',
          unsupportedConstraints: [
            { category: 'duration', userText: 'make it shorter' },
          ],
        },
      }),
      'needs_clarification',
    ],
    [
      'an unsupported-only refinement',
      plan({
        outcome: 'interpreted',
        patch: UNCHANGED_PATCH,
        preservation: UNCHANGED_PRESERVATION,
        unsupportedConstraints: [
          { category: 'activity', userText: 'for running' },
        ],
      }),
      'needs_clarification',
    ],
  ])(
    'keeps the applied intent when the result is %s',
    async (_label, response, status) => {
      const world = createWorld();
      world.planner.planRefinement.mockResolvedValue(response);

      const { session } = await execute(world);

      expect(session.pendingRefinement?.status).toBe(status);
      expect(session.aiSafe.intent).toEqual(INTENT);
      expect(session.execution).toBe(GENERATED);
    },
  );

  it('keeps the applied state and counts the attempt when interpretation fails', async () => {
    const world = createWorld();
    world.planner.planRefinement.mockRejectedValue(
      AiInterpretationError.timedOut(),
    );

    await expect(execute(world)).rejects.toBeInstanceOf(AiInterpretationError);

    const stored = world.store.get(TOKEN);
    expect(stored?.aiSafe.intent).toEqual(INTENT);
    expect(stored?.pendingRefinement).toBeNull();
    expect(stored?.execution).toBe(GENERATED);
    expect(stored?.refinementAttempts).toBe(1);
    expect(world.sessions.releaseRefinementLock).toHaveBeenCalledWith(
      TOKEN,
      'lock-1',
    );
  });

  it('interprets every refinement against the latest applied intent, replacing the pending one', async () => {
    const world = createWorld();

    await execute(world);
    await execute(world);

    const requests = world.planner.planRefinement.mock.calls.map(
      ([request]) => request,
    );
    expect(requests[1].intent).toEqual(INTENT);
    expect(world.store.get(TOKEN)?.refinementAttempts).toBe(2);
  });

  it('refuses a concurrent refinement of the same session without calling the planner', async () => {
    const world = createWorld();
    world.holdLock();

    expect(await errorCode(execute(world))).toBe('AI_REFINEMENT_IN_PROGRESS');
    expect(world.planner.planRefinement).not.toHaveBeenCalled();
    expect(world.sessions.saveIfUnchanged).not.toHaveBeenCalled();
  });

  it('holds the refinement lease for the configured lease duration and always releases it', async () => {
    const world = createWorld();

    await execute(world);

    expect(world.sessions.acquireRefinementLock).toHaveBeenCalledWith(
      TOKEN,
      AI_REFINEMENT_LEASE_MS,
    );
    expect(world.sessions.releaseRefinementLock).toHaveBeenCalledWith(
      TOKEN,
      'lock-1',
    );
  });

  it('never overwrites a session that changed while the refinement was interpreted', async () => {
    const world = createWorld();
    world.planner.planRefinement.mockImplementation(() => {
      const current = world.store.get(TOKEN) as AiSession;
      world.store.set(TOKEN, {
        ...current,
        destination: {
          status: 'publishing',
          attemptId: 'publish-1',
          startedAt: NOW.toISOString(),
          spotifyPlaylist: null,
        },
        updatedAt: new Date(NOW.getTime() + 1).toISOString(),
      });
      return Promise.resolve(lessMainstream());
    });

    expect(await errorCode(execute(world))).toBe('AI_REFINEMENT_SUPERSEDED');
    expect(world.store.get(TOKEN)?.destination?.status).toBe('publishing');
    expect(world.store.get(TOKEN)?.pendingRefinement).toBeNull();
  });

  it('never overwrites a destination written in the same millisecond as the reservation', async () => {
    const world = createWorld();
    world.planner.planRefinement.mockImplementation(() => {
      const current = world.store.get(TOKEN) as AiSession;
      world.store.set(TOKEN, {
        ...current,
        destination: {
          status: 'transfer_prepared',
          preparedAt: current.updatedAt,
          transfer: {
            url: 'https://soundiiz.com/go/import-playlist/abc',
            expiresAt: EXPIRES_AT,
            trackCount: 3,
          },
        },
      });
      return Promise.resolve(lessMainstream());
    });

    expect(await errorCode(execute(world))).toBe('AI_REFINEMENT_SUPERSEDED');
    expect(world.store.get(TOKEN)?.destination?.status).toBe(
      'transfer_prepared',
    );
  });

  it.each<[string, Partial<AiSession>, AiSessionErrorCode]>([
    ['not generated yet', { execution: null }, 'AI_PLAYLIST_NOT_GENERATED'],
    [
      'still generating',
      {
        execution: {
          status: 'generating',
          attemptId: 'a',
          startedAt: GENERATED_AT,
        },
      },
      'AI_PLAYLIST_NOT_GENERATED',
    ],
    [
      'waiting for a first-turn clarification',
      {
        clarification: {
          reason: 'ambiguous_request',
          seedType: null,
          limit: null,
          names: [],
          unsupportedConstraints: [],
          options: [],
        },
      },
      'AI_SESSION_NOT_READY',
    ],
    ...(
      [
        {
          status: 'published',
          publishedAt: NOW.toISOString(),
          spotifyPlaylist: {
            spotifyId: '37i9dQZF1DX0XUsuxWHRQd',
            spotifyUrl: null,
          },
          savedToLibrary: true,
        },
        {
          status: 'publish_incomplete',
          failedAt: NOW.toISOString(),
          spotifyPlaylist: null,
        },
        {
          status: 'publishing',
          attemptId: 'publish-1',
          startedAt: NOW.toISOString(),
          spotifyPlaylist: null,
        },
        {
          status: 'transfer_prepared',
          preparedAt: NOW.toISOString(),
          transfer: {
            url: 'https://soundiiz.com/go/import-playlist/abc',
            expiresAt: '2026-09-28T11:00:00.000Z',
            trackCount: 3,
          },
        },
      ] satisfies AiSessionDestination[]
    ).map((destination): [string, Partial<AiSession>, AiSessionErrorCode] => [
      `already ${destination.status}`,
      { destination },
      'AI_REFINEMENT_UNAVAILABLE',
    ]),
    [
      'out of refinements',
      { refinementAttempts: DEFAULT_AI_REFINEMENTS_PER_SESSION },
      'AI_REFINEMENT_LIMIT_REACHED',
    ],
  ])(
    'refuses a session %s without any planner call or write',
    async (_label, overrides, code) => {
      const world = createWorld(storedSession(overrides));

      expect(await errorCode(execute(world))).toBe(code);
      expect(world.planner.planRefinement).not.toHaveBeenCalled();
      expect(world.sessions.saveIfUnchanged).not.toHaveBeenCalled();
      expect(world.sessions.acquireRefinementLock).not.toHaveBeenCalled();
    },
  );

  it('reads the per-session limit from configuration', async () => {
    const world = createWorld(storedSession({ refinementAttempts: 1 }), {
      AI_REFINEMENTS_PER_SESSION: '2',
    });

    await execute(world);

    expect(await errorCode(execute(world))).toBe('AI_REFINEMENT_LIMIT_REACHED');
    expect(world.planner.planRefinement).toHaveBeenCalledTimes(1);
  });

  it('fails fast on an invalid per-session limit', () => {
    expect(() =>
      createWorld(storedSession(), { AI_REFINEMENTS_PER_SESSION: '0' }),
    ).toThrow('Invalid AI_REFINEMENTS_PER_SESSION');
  });

  it.each([
    ['missing', null, null],
    [
      'owned by another user',
      storedSession({ ownerUserId: 'user-1' }),
      'user-2',
    ],
    ['expired', storedSession({ expiresAt: '2026-09-28T11:59:59.000Z' }), null],
  ])('reports a %s session as not found', async (_label, session, userId) => {
    const world = createWorld(session);

    expect(await errorCode(execute(world, userId))).toBe(
      'AI_SESSION_NOT_FOUND',
    );
    expect(world.planner.planRefinement).not.toHaveBeenCalled();
  });

  it('refines an authenticated session only for its owner', async () => {
    const world = createWorld(storedSession({ ownerUserId: 'user-1' }));

    const { session } = await execute(world, 'user-1');

    expect(session.pendingRefinement?.status).toBe('proposed');
    expect(session.ownerUserId).toBe('user-1');
  });

  it('logs metadata only', async () => {
    const log = jest.spyOn(Logger.prototype, 'log').mockImplementation();
    const world = createWorld();

    await execute(world);

    const logged = log.mock.calls
      .map(([message]) => String(message))
      .join('\n');
    expect(JSON.parse(logged)).toEqual({
      event: 'ai.refinement.proposed',
      status: 'proposed',
      clarificationReason: null,
      promptVersion: 'refinement-v1',
      attempt: 1,
      durationMs: expect.any(Number) as number,
    });
    expect(logged).not.toContain(REFINEMENT);
    expect(logged).not.toContain('Radiohead');
  });
});
